### ISSUE TITLE
sendPostData function returns nothing

### ISSUE THREAD

**Issue by pedrogclp** [shakee93/fonoapi#1]
var_dump() of sendPostData returns bool(false)

**Comment by shakee93** [comment]
Did you try with the demo files ? it seems to be working. can you attach the code please

**Comment by pedrogclp** [comment]
Yes I did, I don't know why its returning false, I just unzip the demo, put it the generated key and tried it. Maybe I'm doing something wrong.. I tried to put other random url to know if cURL was working, and it worked.

**Comment by shakee93** [comment]
I just made a commit. i have added debugging for curl.

you can now use 
fonoApi::init($apiKey) -- initiate
fonoApi::debug($apiKey) -- debug

check the demo file

**Comment by pedrogclp** [comment]
Thanks you, I'll test ASAP

**Comment by pedrogclp** [comment]
This is from debugger:
"ERROR : Curl Failed | innerException : SSL certificate problem: unable to get local issuer certificate"

**Comment by pedrogclp** [comment]
I solved: [http://unitstep.net/blog/2009/05/05/using-curl-in-php-to-access-https-ssltls-protected-sites/](here)

`curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);`

And it works

**Comment by shakee93** [comment]
Great. its a common server config issue. but disabling verifier makes all your requests insecure that is not recommended.

There is another approach using .pem file
http://stackoverflow.com/questions/28858351/php-ssl-certificate-error-unable-to-get-local-issuer-certificate

you could give it a try.

**Comment by pedrogclp** [comment]
Thanks you!

**Comment by pedrogclp** [comment]
To configure WAMP:
1.- **Download** the CA Certificate from this link: [https://curl.haxx.se/ca/cacert.pem](url)
2.- Open **php.ini**
3.- Look for **curl.cainfo** and paste the **absolute path** where you have download the Certificate.
`/* Example: curl.cainfo = "C:\wamp\htdocs\cert\cacert.pem" */`
4.- **Restart** WAMP.
5.- **It works!**
