### ISSUE TITLE
Is is possible to get all the devices in one request?

### ISSUE THREAD

**Issue by guilherme6191** [shakee93/fonoapi#10]
Hey guys.
Nice API!

I needed all the devices, either in a json file or doing only one request. It's for a school project lol

Is that possible?
Thanks!

**Comment by shakee93** [comment]
Sorry it is not possible. you can get maximum of 100 devices per request.

Thanks

**Comment by nashwaan** [comment]
Hi @shakee93 ,

Very good job on the API. I have a similar question: If the API limits the result to 100 devices per request, then how to get the next 100? I am trying to get all **samsung** devices.

**Comment by shakee93** [comment]
Sorry currently its a no.. i am working on the second version of the api. ill try to add this to the list.

Thanks

**Comment by nashwaan** [comment]
Thanks @shakee93  for considering this in the next version.

Any estimates on the timeline of the next api?

**Comment by shakee93** [comment]
I have already started working on the second version. but unfortunately i cannot guarantee a timeline as i am maintaining this with my full time job. ill try to publish it as soon as possible.

Thank you
