### ISSUE TITLE
TOKEN ERROR

### ISSUE THREAD

**Issue by altamash-ak** [shakee93/fonoapi#15]
hey @shakee93 
the token you provied form "[https://fonoapi.freshpixl.com/](url)" is not working and also will it show the latest price

**Comment by shakee93** [comment]
Please help me with the error you get. and it will not have the prices

**Comment by altamash-ak** [comment]
hey well it working fine now but it was giving this error

"Invalid or Blocked Token. Generate a Token at fonoapi.freshpixl.com"

**Comment by hirenkanetiya** [comment]
How this error solved ? i also face the same issue in angular HTTP post call.

**Comment by shakee93** [comment]
Generate a token and try again. if it still doesnt work reproduce the code so i can take a look.
