### ISSUE TITLE
I can't get the data

### ISSUE THREAD

**Issue by vignesh1raj** [shakee93/fonoapi#18]
I'm getting error like below
PHP Notice:  Undefined index: HTTP_HOST
PHP Notice:  Undefined index: REQUEST_URI

And also when i given referrer as some website. And run the demo.php its returning like ERROR : Curl Failed

Why we need to pass this parameter and what is the solution for that.
Thanks,
VIGNESH KUMAR K

**Comment by shakee93** [comment]
Please try the latest version it is fixed

**Comment by vignesh1raj** [comment]
Ya its fixed now, upgraded the curl

**Comment by shakee93** [comment]
Thank you !!! 😉
