### ISSUE TITLE
Adding languages

### ISSUE THREAD

**Issue by spikerx94** [shakee93/fonoapi#22]
Is there an option to change the language? March for example Polish Marzec.

**Comment by shakee93** [comment]
Sorry you will have to use your app to translate. it will be complicated to localize the data

**Comment by spikerx94** [comment]
I can do it with javascript? Is there a better way?

Text replacement in javascript is problematic that affects positioning. Google sees how the English text is judged

**Comment by shakee93** [comment]
Google translate is the best option as far as i know.

**Comment by spikerx94** [comment]
Okay thanks

I have yet another question as to whether it is possible to "lock" the model name. For example, "Apple iPhone 7" is the first to display 7 plus. In php to force to show the first result I used

`$i=0;
            foreach ($res as $mobile)if ($i < 1) {
                if (!empty($mobile->DeviceName))    echo "<p><strong>Wprowadzono na rynek: </strong> ". $mobile->announced . "</p>";
                if (!empty($mobile->Brand))         echo "<p><strong>Typ wyświetlacza: </strong>". $mobile->type . "</p>";
                if (!empty($mobile->cpu))           echo "<p><strong>Wielkość wyświetlacza: </strong>" . $mobile->size . "</p>";
                if (!empty($mobile->status))        echo "<p><strong>Rozdzielczość wyświetlacza: </strong>" . $mobile->resolution . "</p>";
                if (!empty($mobile->dimensions))    echo "<p><strong>Dostępne kolory: </strong>" . $mobile->colors . "</p>";
                if (!empty($mobile->_4g_bands))     echo "<p><strong>Ochrona wyświetlacza: </strong>" .$mobile->protection . "</p>";
                if (!empty($mobile->_4g_bands))     echo "<p><strong>Typ złącza: </strong>" .$mobile->usb . "</p>";
                $i +=1;`

I currently appear to receive data from iphone 7 plus, and i want from iphone 7. Unfortunately i can not use javascript
So can I somehow filter the name?

**Comment by shakee93** [comment]
for this version of API. there is no sort or filter options. so you will have to do it with the data you get from the API. as of the above case you can use the php 'array_reverse' [doc](http://php.net/manual/en/function.array-reverse.php)  method. it will reverse the order
