### ISSUE TITLE
Only getting 100 results

### ISSUE THREAD

**Issue by channaveer** [shakee93/fonoapi#27]
Hi, 
Thank you so much for your efforts to come up with such a beautiful API code.

I am having a query if I use the following code, it will return at max 100 records as per your API. 

$devices = fonoApi::getDevice('samsung');

Is there any other way to get the next 100 records or all the devices till date of a particular brand.

Thanks is advance.

**Comment by shakee93** [comment]
related to #10

**Comment by moeinkarimi1984** [comment]
hi
thanks for your api

@channaveer you can read from this char by char
i wrote php code with searching array based. that take all device from this.
e.g. samsung a, samsung b, and ,,,,,
each character has usually no more than 100 device
in some case samsung g === galaxy maybe that is more than 100 then you must change code to
samsung galaxy a, samsung galaxy b,....

and check that witch charecter is more than 100, that's the way
think and try
