### ISSUE TITLE
Doesn't work with Advanced Rest Client (Chrome Extension)

### ISSUE THREAD

**Issue by ThunderRoid** [shakee93/fonoapi#3]
![untitled](https://cloud.githubusercontent.com/assets/3328263/14483532/a6edcdf0-0169-11e6-97f1-3d16f92a6a67.png)

Responce 

{"status":"error","message":"Invalid or Blocked Token. Generate a Token at fonoapi.freshpixl.com","innerException":null}

**Comment by shakee93** [comment]
![image](https://cloud.githubusercontent.com/assets/14835725/14491076/4a76ec20-0194-11e6-83b4-180c2a8ff557.png)
![image](https://cloud.githubusercontent.com/assets/14835725/14491085/5c04f9b4-0194-11e6-80c2-b609f5ae7fac.png)

i have just checked the with the extension you have mentioned it seems working. please try again with a different token. it seems token is invalid or mistyped.

**Comment by ThunderRoid** [comment]
You used the PATCH method instead of POST. Thanks
