### ISSUE TITLE
Get all brand and all models

### ISSUE THREAD

**Issue by paulomac1000** [shakee93/fonoapi#30]
I'm creating project for my university and I need all phones with parameters. I want to use Your API, but I don't know all phone names. I tried to get phones by brand name, but f.e. Samsung has about 1500 models and API limit result to 100 items. Is there any way to get more result or get only all models for specified brand? Or can You implement pagination of result?

**Comment by paulomac1000** [comment]
resolved problem by myself

**Comment by watahell** [comment]
How did you solve this?
