### ISSUE TITLE
Newer device not added

### ISSUE THREAD

**Issue by vijai1996** [shakee93/fonoapi#4]
Hello,
This looks like a neat and good api for finding mobile specifications but I see the database isnt updated yet. I couldnt find specs for nexus 6p and iphone 6s+ for example. May I know how fast is the database updated?

**Comment by shakee93** [comment]
It is updated once a month or so.  iphone 6 plus already available, nexus 6p was missing just added now.

try query iphone.

you can try here
http://codepen.io/Shakee93/pen/reYvow
