### ISSUE TITLE
Please write HTTP method in README

### ISSUE THREAD

**Issue by pinkienort** [shakee93/fonoapi#46]
There are api descriptions in README, but there is no description about HTTP method.

**Comment by pinkienort** [comment]
pr is #47

**Comment by alexandruspataru** [comment]
Maybe you could learn a bit about the "Do It Yourself" method? Anyway, this is an example of how you can get it done:

`https://fonoapi.freshpixl.com/v1/getdevice?token=86b89476caaf66eda3f21279b7711afc&device=z5&brand=sony`

whereas we have the following parameters:

**token** - your personal token
**device** - the device you're looking for
**brand** - the brand that owns the phone - keep in mind that you can always search for device=Sony+Z5, without including the brand

**Comment by pinkienort** [comment]
I'm sorry, I noticed that the query was wrong, I found that I can access GET or POST. So I will add a commit of the fix to the pull request.

The example is very easy to understand, I can see that the API can be accessed with the GET method. However, the README does not have that information, it is confusing. Therefore, it is helpful to explain explicitly whether the API uses which method.
