### ISSUE TITLE
Access-Control-Allow-Origin response header is missing

### ISSUE THREAD

**Issue by aviv-dw** [shakee93/fonoapi#59]
I am trying to get the data from the API but keep getting CORS error, even though data is fetched .

After searching about this problem it seems that you are missing the
Access-Control-Allow-Origin response header.

Here is a link to the issue in Stackoverflow:
https://stackoverflow.com/questions/46737291/cors-error-but-data-is-fetched-regardless 

Could you please fix this issue?

**Comment by shakee93** [comment]
fixed this issue !!

**Comment by aviv-dw** [comment]
Thank you for the very quick response and fix! It is working now.
