### ISSUE TITLE
Filter by years

### ISSUE THREAD

**Issue by rusmichal** [shakee93/fonoapi#7]
Hello.

Thank you for you great API. I have question is it possible to add parameter 'year' or something like that to method getdevice? We need to filter device.

**Comment by shakee93** [comment]
You are Welcome. Currently released date is not available on database so would not be able to add it. ill try to collect release date of mobiles after that you can have the release date filter. announced date is possible now.

Thanks

**Comment by AngelinCalu** [comment]
Maybe there is a way we can help keeping the info from the database updated, as for example "Samsung Galaxy J5 (2016)" has old information regarding releasing date. (it was updated on GSMArena after "collecting" info).

**Comment by shakee93** [comment]
@AngelinCalu Yeah It's a good idea. ill work on it and update this soon.

**Comment by shakee93** [comment]
closing this issue. follow this issue for the updates regarding this feature #17
