### ISSUE TITLE
check quality info should be removed

### ISSUE THREAD

**Issue by AngelinCalu** [shakee93/fonoapi#8]
![scrap-filter](https://cloud.githubusercontent.com/assets/4613739/17457366/aa950c9e-5bfe-11e6-9a24-4e391a9a2d1f.PNG)

Maybe you should remove "check quality" text from some descriptions before adding it to the database as it's not making too much sense to be there.  

I am using the jquery to return objects and I needed to add something like the following to extra "parse" content:

`obj[key] = obj[key].replace(/, check quality/g, "");`

**Comment by shakee93** [comment]
Thank you for the feedback. it is now been removed.
